language: julia

os:
  - linux
  - osx

julia:
  - release
  - nightly

branches:
  only:
    - master

notifications:
  email: false

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.build("BenchmarkProfiles"); Pkg.test("BenchmarkProfiles"; coverage=true)'
